/*
 * This file is automatically generated by Qt Design Studio.
 * Do not change.
*/

// Static QML modules - no plugin imports needed
// All QML modules are statically linked via qt6_import_qml_plugins()

